In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [12]:
!pip install pandas
import pandas as pd
import numpy as np
!pip install matplotlib
import matplotlib as plt
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
print(plt.__version__)

3.3.3


In [15]:
print(np.__version__)

1.19.5


In [37]:
a=np.array([43])
print(a)

[43]


In [38]:
b=np.array([1,2,3,4,5])
print(b)

[1 2 3 4 5]


In [26]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [27]:
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [39]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
1
2
3


In [40]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [41]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [42]:
print(arr[0], arr[1])

1 2


In [43]:
print(arr[0] + arr[1])

3


In [44]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st dim: ', arr[0,1])

2nd element on 1st dim:  2


In [45]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st dim: ', arr[0,1])

2nd element on 1st dim:  2


In [46]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1,-1,1])

11


In [48]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1,-1,-1])

12


In [49]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5])

[2 3 4 5]


In [50]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[:5])

[1 2 3 4 5]


In [51]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:])

[2 3 4 5 6 7 8 9]


In [53]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5:2])

[2 4]


In [54]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[::2])

[1 3 5 7 9]


In [55]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [57]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3]
 [7 8]]
